package com.zs.example.greendaotest.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig schoolDaoConfig;

    private final MovieDao movieDao;
    private final UserDao userDao;
    private final SchoolDao schoolDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDaoConfig = daoConfigMap.get(MovieDao.class).clone();
        movieDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        schoolDaoConfig = daoConfigMap.get(SchoolDao.class).clone();
        schoolDaoConfig.initIdentityScope(type);

        movieDao = new MovieDao(movieDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        schoolDao = new SchoolDao(schoolDaoConfig, this);

        registerDao(Movie.class, movieDao);
        registerDao(User.class, userDao);
        registerDao(School.class, schoolDao);
    }
    
    public void clear() {
        movieDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        schoolDaoConfig.clearIdentityScope();
    }

    public MovieDao getMovieDao() {
        return movieDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public SchoolDao getSchoolDao() {
        return schoolDao;
    }

}
